server:
  port: 8485

spring:
  application:
    name: nexus-play-backend
  profiles:
    active: "${APP_SPRING_PROFILE:dev}"
    
app:
  jwt:
    secret: "${APP_CHAVE_SECRETA_JWT}"
    expiracao-ms: 3600000

rawg:
  url: https://api.rawg.io/api
  api-key: "${RAWG_API_KEY}"
